# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor", path: "../"
gem "cmor_cms", path: "../cmor_cms"
gem "cmor_cms_backend", path: "../cmor_cms_backend"
gem "rails", "~> 6.1", "< 6.2"
