require 'acts_as_list'
require 'acts_as_published'
require 'friendly_id'
require 'cmor_core_frontend'
require 'rao-resources_controller'
require 'rao-view_helper'
require 'haml-rails'

require 'cmor/core/model/collection_concern'
require 'cmor/core/model/localization_concern'
require 'cmor/core/model/identifier_concern'
require 'cmor/galleries'
