defaults:
  permissions:
    - cmor/cms/backend/engine
    - cmor/cms/backend/home/index
    - cmor/cms/content_box/index
    - cmor/cms/content_box/show
    - cmor/cms/content_box/new
    - cmor/cms/content_box/create
    - cmor/cms/content_box/edit
    - cmor/cms/content_box/update
    - cmor/cms/content_box/destroy
    - cmor/cms/layout/index
    - cmor/cms/layout/show
    - cmor/cms/layout/new
    - cmor/cms/layout/create
    - cmor/cms/layout/edit
    - cmor/cms/layout/update
    - cmor/cms/layout/destroy
    - cmor/cms/navigation/index
    - cmor/cms/navigation/show
    - cmor/cms/navigation/new
    - cmor/cms/navigation/create
    - cmor/cms/navigation/edit
    - cmor/cms/navigation/update
    - cmor/cms/navigation/destroy
    - cmor/cms/navigation_item/index
    - cmor/cms/navigation_item/show
    - cmor/cms/navigation_item/new
    - cmor/cms/navigation_item/create
    - cmor/cms/navigation_item/edit
    - cmor/cms/navigation_item/update
    - cmor/cms/navigation_item/destroy
    - cmor/cms/page/index
    - cmor/cms/page/show
    - cmor/cms/page/new
    - cmor/cms/page/create
    - cmor/cms/page/edit
    - cmor/cms/page/update
    - cmor/cms/page/destroy
    - cmor/cms/partial/index
    - cmor/cms/partial/show
    - cmor/cms/partial/new
    - cmor/cms/partial/create
    - cmor/cms/partial/edit
    - cmor/cms/partial/update
    - cmor/cms/partial/destroy
    - cmor/cms/redirect/index
    - cmor/cms/redirect/show
    - cmor/cms/redirect/new
    - cmor/cms/redirect/create
    - cmor/cms/redirect/edit
    - cmor/cms/redirect/update
    - cmor/cms/redirect/destroy
    - cmor/cms/template/index
    - cmor/cms/template/show
    - cmor/cms/template/new
    - cmor/cms/template/create
    - cmor/cms/template/edit
    - cmor/cms/template/update
    - cmor/cms/template/destroy
    - cmor/cms/add_homepages_service/new
    - cmor/cms/add_homepages_service/create
    - cmor/cms/import_partials_service/new
    - cmor/cms/import_partials_service/create
  roles:
    cmor/cms/administrator:
      - cmor/cms/backend/engine
      - cmor/cms/backend/home/index
      - cmor/cms/content_box/index
      - cmor/cms/content_box/show
      - cmor/cms/content_box/new
      - cmor/cms/content_box/create
      - cmor/cms/content_box/edit
      - cmor/cms/content_box/update
      - cmor/cms/content_box/destroy
      - cmor/cms/layout/index
      - cmor/cms/layout/show
      - cmor/cms/layout/new
      - cmor/cms/layout/create
      - cmor/cms/layout/edit
      - cmor/cms/layout/update
      - cmor/cms/layout/destroy
      - cmor/cms/navigation/index
      - cmor/cms/navigation/show
      - cmor/cms/navigation/new
      - cmor/cms/navigation/create
      - cmor/cms/navigation/edit
      - cmor/cms/navigation/update
      - cmor/cms/navigation/destroy
      - cmor/cms/navigation_item/index
      - cmor/cms/navigation_item/show
      - cmor/cms/navigation_item/new
      - cmor/cms/navigation_item/create
      - cmor/cms/navigation_item/edit
      - cmor/cms/navigation_item/update
      - cmor/cms/navigation_item/destroy
      - cmor/cms/page/index
      - cmor/cms/page/show
      - cmor/cms/page/new
      - cmor/cms/page/create
      - cmor/cms/page/edit
      - cmor/cms/page/update
      - cmor/cms/page/destroy
      - cmor/cms/partial/index
      - cmor/cms/partial/show
      - cmor/cms/partial/new
      - cmor/cms/partial/create
      - cmor/cms/partial/edit
      - cmor/cms/partial/update
      - cmor/cms/partial/destroy
      - cmor/cms/redirect/index
      - cmor/cms/redirect/show
      - cmor/cms/redirect/new
      - cmor/cms/redirect/create
      - cmor/cms/redirect/edit
      - cmor/cms/redirect/update
      - cmor/cms/redirect/destroy
      - cmor/cms/template/index
      - cmor/cms/template/show
      - cmor/cms/template/new
      - cmor/cms/template/create
      - cmor/cms/template/edit
      - cmor/cms/template/update
      - cmor/cms/template/destroy
      - cmor/cms/add_homepages_service/new
      - cmor/cms/add_homepages_service/create
      - cmor/cms/import_partials_service/new
      - cmor/cms/import_partials_service/create
    cmor/cms/reviewer:
      - cmor/cms/backend/engine
      - cmor/cms/backend/home/index
      - cmor/cms/content_box/index
      - cmor/cms/content_box/show
      - cmor/cms/layout/index
      - cmor/cms/layout/show
      - cmor/cms/navigation/index
      - cmor/cms/navigation/show
      - cmor/cms/navigation_item/index
      - cmor/cms/navigation_item/show
      - cmor/cms/page/index
      - cmor/cms/page/show
      - cmor/cms/partial/index
      - cmor/cms/partial/show
      - cmor/cms/redirect/index
      - cmor/cms/redirect/show
      - cmor/cms/template/index
      - cmor/cms/template/show