source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor-core-api", path: "../cmor-core-api"
gem "cmor", path: "../"
gem "cmor-blog", path: "../cmor-blog"
gem 'rails', '6.0.0.0'
