# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "cmor", path: "../"
gem "cmor_api", path: "../cmor_api"

gem "cmor_blog", path: "../cmor_blog"
gem "cmor_blog_backend", path: "../cmor_blog_backend"
gem "cmor_user_area", path: "../cmor_user_area"
gem "cmor_user_area_backend", path: "../cmor_user_area_backend"
gem "cmor_cms", path: "../cmor_cms"
gem "cmor_cms_backend", path: "../cmor_cms_backend"