source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor-core-backend", path: "../cmor-core-backend"
gem "cmor", path: "../"
gem "rails", "~> 6.1", "< 6.2"
