# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor", path: "../"
gem "cmor-cms", path: "../cmor-cms"
gem "rails", "~> 6.1", "< 6.2"
