# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e4cc9cac29358ae5036789380351716c9f95ef78a6b2db3ba7abd4da966b740d230fd238307e650500b84489950483d1b74afd373be6bbfa02a4230a1a3c69f

test:
  secret_key_base: 7a3c0de0b4833f5116c3f9b0092e6178702a7a71c83665c29bcfdf7c1d09cc9b23212a73ef41a15df505c74ab7dbec8520189a23c13cdc38cef127c7ef3b216e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
