source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem 'cmor', path: '../'
gem 'cmor_files', path: '../cmor_files'
gem 'cmor-core-backend', path: '../cmor-core-backend'
gem "rails", "~> 6.1", "< 6.2"
