require 'acts_as_list'
require 'markup-rails'
require 'acts_as_published'
require 'cmor_core_frontend'
require 'haml-rails'
require 'mini_magick'
require 'rao-view_helper'
require 'friendly_id'

require 'cmor/testimonials'