source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor", path: ".."
gem "cmor-core", path: "../cmor-core"
gem "cmor-core-api", path: "../cmor-core-api"
gem "cmor-core-backend", path: "../cmor-core-backend"
gem "cmor-testimonials", path: "../cmor-testimonials"
gem 'rails', '~> 7.0'
gem "rao-api-resources_controller", path: "~/projects/gems/rao/rao-api-resources_controller"
