source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor_core", path: "../cmor_core"
gem "cmor_core_backend", path: "../cmor_core_backend"
gem "cmor", path: "../"
gem "rails", "~> 6.1", "< 6.2"
