source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem 'cmor', path: '../'
gem 'cmor_core', path: '../cmor_core'
gem 'rails', '7.0.4'
gem 'psych', '< 4'
