require "responders"
require "cmor_core_frontend"
require "cmor_contact"
# require "cmor_core"
# require "cmor_core_frontend"
# require "haml-rails"
# require "simple_form"
# require "coffee-rails"

require "cmor/contact/frontend"