# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
git "https://github.com/content-management-on-rails/cmor", branch: "feature/cmor-core-api" do
  gem 'cmor_core'
  gem 'cmor_core_backend'
  gem 'cmor-core-api'
  gem 'cmor'
end
gem "cmor-faq", path: "../cmor-faq"
gem "rails", "~> 7.0"
gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"
