# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
git "https://github.com/content-management-on-rails/cmor", branch: "feature/cmor-core-api" do
  gem 'cmor_core'
  gem 'cmor_core_backend'
  gem 'cmor'
end
gem "rails", "~> 7.0"
gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"
gem "rao-resources_controller", github: "rails-add-ons/rao", branch: "main", glob: "rao-resources_controller/*.gemspec"

