source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "rails", "~> 6.1", "< 6.2"
gem "cmor", path: "../"
gem "cmor-core-backend", path: "../cmor-core-backend"
gem "cmor_multi_tenancy", path: "../cmor_multi_tenancy"
