source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "cmor", path: "../"
gem "cmor_multi_tenancy", path: "../cmor_multi_tenancy"
gem "cmor_core_backend", path: "../cmor_core_backend"
gem 'rails', '6.0.0.0'
