require 'cmor/suite'

# require 'cmor_audits'
require 'cmor_blog'
require 'cmor_blog_backend'
require 'cmor_carousels'
require 'cmor_carousels_backend'
require 'cmor_cms'
require 'cmor_cms_backend'
require 'cmor_contact'
require 'cmor_contact_backend'
require 'cmor_files'
require 'cmor_files_backend'
require 'cmor_galleries'
require 'cmor_galleries_backend'
require 'cmor_legal'
require 'cmor_legal_frontend'
require 'cmor_links'
require 'cmor_links_backend'
# require 'cmor_multi_tenancy'
# require 'cmor_multi_tenancy_frontend'
require 'cmor_partners'
require 'cmor_partners_frontend'
require 'cmor_rbac'
require 'cmor_rbac_backend'
require 'cmor_security'
require 'cmor_seo'
require 'cmor_seo_frontend'
require 'cmor_showcase'
require 'cmor_showcase_frontend'
require 'cmor_tags'
require 'cmor_tags_backend'
require 'cmor_testimonials'
require 'cmor_testimonials_backend'
# require 'cmor_transports'
require 'cmor_user_area'
require 'cmor_user_area_backend'
require 'cmor-core-api'
require 'cmor-core-api-backend'
require 'cmor-system'
