ignore:
- 'Guardfile'
- 'spec/dummy/**/*'
- 'spec/rails_helper.rb'
- 'spec/spec_helper.rb'
- Gemfile:
  - Style/StringLiterals
  - Layout/TrailingEmptyLines
- Guardfile:
  - Style/StringLiterals
  - Style/PercentLiteralDelimiters
  - Layout/ExtraSpacing
- Rakefile:
  - Style/StringLiterals
  - Layout/ExtraSpacing
