# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor", path: "../"
gem "cmor-core", path: "../cmor-core"
gem "rails", "~> 6.1", "< 6.2"

gem 'tatoru-client', git: 'https://github.com/tatoru-antivirus/tatoru-client-ruby' # path: '~/projects/tatoru/tatoru-client-ruby'
gem 'tatoru-client-rails', git: 'https://github.com/tatoru-antivirus/tatoru-client-rails' # path: '~/projects/tatoru/tatoru-client-rails'
