require "bundler/setup"

APP_RAKEFILE = File.expand_path("spec/dummy/Rakefile", __dir__)
load "rails/tasks/engine.rake" if File.exists?(APP_RAKEFILE)

load "rails/tasks/statistics.rake"

require "bundler/gem_tasks"

require "rails/dummy/tasks"