# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem "cmor", path: "../"
gem "cmor_seo", path: "../cmor_seo"
gem "cmor_core_backend", path: "../cmor_core_backend"
gem "rails", "~> 6.1", "< 6.2"
