# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem "cmor", path: "../"
gem "cmor_cms", path: "../cmor_cms"
gem 'rails', '7.0.4'
