require 'cmor_core'
# require 'cmor_comments'
require 'acts_as_list'
require 'acts_as_published'
require 'friendly_id'
require 'html2markdown'
require 'kaminari'
require 'kramdown'

require 'cmor/blog'