require 'cmor_core_frontend'
require 'active_storage_validations'
require 'acts_as_list'
require 'acts_as_published'
require 'friendly_id'
require 'haml-rails'
require 'kramdown'
require 'rails-i18n'
require 'rao-resources_controller'
require 'rao-service'
require 'rao-component'

require 'cmor/core/model/localization_concern'
require 'cmor/blog'
