source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem 'cmor', path: '../'
gem 'cmor_cms', path: '../cmor_cms'
gem 'cmor_core_backend', path: '../cmor_core_backend'
gem 'rails', '6.0.0.0'
