source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec
gem 'cmor', path: '../'
gem "rao-active_collection", path: "~/projects/gems/rao/rao-active_collection"
gem "rails", "~> 6.1", "< 6.2"
