require 'cmor_core_frontend'
require 'authlogic'
require 'active_model_serializers'
require 'rao-component'
require 'rao-view_helper'
require 'rao-service'
require 'rao-resources_controller'
require 'rao-service_controller'
require 'simple_form'
require 'active_model_otp'
require 'rqrcode'
require 'aasm'

require 'cmor/user_area'