source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem 'cmor', path: '../'
gem 'cmor_showcase', path: '../cmor_showcase'
gem 'cmor_core_backend', path: '../cmor_core_backend'
